// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: gsgSHLmWb1QSgLbNnKk81t
// Component: ZpIM-VeN3n
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: gsgSHLmWb1QSgLbNnKk81t/projectcss
import * as sty from "./PlasmicTestPage.module.css"; // plasmic-import: ZpIM-VeN3n/css

export const PlasmicTestPage__VariantProps = new Array();

export const PlasmicTestPage__ArgProps = new Array();

function PlasmicTestPage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        />
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTestPage__ArgProps,
      internalVariantPropNames: PlasmicTestPage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicTestPage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTestPage";
  } else {
    func.displayName = `PlasmicTestPage.${nodeName}`;
  }
  return func;
}

export const PlasmicTestPage = Object.assign(
  // Top-level PlasmicTestPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicTestPage
    internalVariantProps: PlasmicTestPage__VariantProps,
    internalArgProps: PlasmicTestPage__ArgProps
  }
);

export default PlasmicTestPage;
/* prettier-ignore-end */
